### ISSUE TITLE
Working Example not present

### ISSUE THREAD

**Issue by sr-bansal** [marc-christian-schulze/structs4java#2]
Please provide working example.

**Comment by marc-christian-schulze** [comment]
Hello @sr-bansal,
could you please detail what you‘re looking for? There‘re already example structure definitions shown on the landing page:
https://github.com/marc-christian-schulze/structs4java#getting-started

**Comment by sr-bansal** [comment]
Hello,

If you can provide working example source in your repository will be great
help to people who will use your repository. Normally atleast one working
sample are provided in source code

**Comment by marc-christian-schulze** [comment]
Hello @sr-bansal,
I've finally had some time to add some examples, cf.
https://github.com/marc-christian-schulze/structs4java?tab=readme-ov-file#examples
