### ISSUE TITLE
No skip option

### ISSUE THREAD

**Issue by jbrentnell** [marc-christian-schulze/structs4java#5]
Most Maven plugins have a configuration option to skip execution.  Usually defaulted to false.  I find this plugin very useful, and would find it even more useful with a skip configuration option.

**Comment by marc-christian-schulze** [comment]
Hello @jbrentnell,
I've just release 1.0.53 with your requested feature, cf. https://github.com/marc-christian-schulze/structs4java?tab=readme-ov-file#plugin-configuration

Should be available in maven central in a couple of mins.

**Comment by marc-christian-schulze** [comment]
Hmm... seems I missed that Travis-CI is no longer free for OSS. So I have to migrate the CI pipeline to somewhere else. Sorry, but then it takes a bit more time to release the requested feature.. :/

**Comment by marc-christian-schulze** [comment]
@jbrentnell 
Pipeline got migrated and new release is published on maven central using version 1.0.60

**Comment by jbrentnell** [comment]
Thank you so much!
