### ISSUE TITLE
how to set default value for one uint32_t field in struct

### ISSUE THREAD

**Issue by walterFor** [marc-christian-schulze/structs4java#6]
how to set default value for one uint32_t field in struct.
struct test{
        uint16_t id;
        uint32_t age; ?? // want to set it 18 as default value
}

**Comment by marc-christian-schulze** [comment]
Hello @walterFor,
unfortunately, default values are not supported (yet).

**Comment by marc-christian-schulze** [comment]
Hey @walterFor,
with version 1.1.0 default values are now supported.
